spring.application.name=videojuegos-api

# H2 en memoria (¡Magia! No necesitas tener nada instalado)
spring.datasource.url=jdbc:h2:mem:videoclubdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA /Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 para ver la base de datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
