server.port=8080
spring.data.mongodb.uri=mongodb+srv://javifullstackdev_db_user:jZXddzNm2eVpDE4q@cluster0.eitdwey.mongodb.net/catalogoLibros?appName=Cluster0
logging.level.org.springframework.data.mongodb=DEBUG
